#####################################
# make file
# Created on: 2016-07-26
# Author: Jugo
#####################################


.PHONY: all clean

all:
	@echo -ne '\n###### Just Global Module not to Build ######\n'
	@echo "\n"
	
clean:
	@echo -ne '\n###### Just Global Module not to Clean ######\n'
	@echo "\n"

