#!/bin/zsh

while true; do
#  log_name="ThreadCount-Tracker.`date +%Y-%m-%d`.log"
  thread_total=0;for b in `pgrep -f controller-tracker`; do; (( thread_total += `ps hH $b | wc -l` ));done
  line="$thread_total, `date +%Y-%m-%dT%H:%M:%S%z|tr -d '\n'`"
  echo $line 
  sleep 1
done
